CREATE TABLE users (id TEXT PRIMARY KEY, google_sub TEXT UNIQUE, display_name TEXT NOT NULL, picture_url TEXT NOT NULL, created_at TEXT NOT NULL);
INSERT INTO users (id, google_sub, display_name, picture_url, created_at) VALUES ('system', NULL, 'System', '', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'));
CREATE TABLE sessions (token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), expires_at TEXT NOT NULL);
CREATE INDEX sessions_user ON sessions(user_id);
ALTER TABLE categories ADD COLUMN created_by_user_id TEXT NOT NULL DEFAULT 'system';
ALTER TABLE categories ADD COLUMN created_at TEXT;
ALTER TABLE transactions ADD COLUMN created_by_user_id TEXT NOT NULL DEFAULT 'system';
ALTER TABLE transactions ADD COLUMN created_at TEXT;
ALTER TABLE budgets ADD COLUMN created_by_user_id TEXT NOT NULL DEFAULT 'system';
ALTER TABLE budgets ADD COLUMN created_at TEXT;
ALTER TABLE recurring_commitments ADD COLUMN created_by_user_id TEXT NOT NULL DEFAULT 'system';
ALTER TABLE recurring_commitments ADD COLUMN created_at TEXT;
ALTER TABLE categorization_rules ADD COLUMN created_by_user_id TEXT NOT NULL DEFAULT 'system';
ALTER TABLE categorization_rules ADD COLUMN created_at TEXT;
ALTER TABLE legacy_exchange_rates ADD COLUMN created_by_user_id TEXT NOT NULL DEFAULT 'system';
ALTER TABLE legacy_exchange_rates ADD COLUMN created_at TEXT;
ALTER TABLE scenarios ADD COLUMN created_by_user_id TEXT NOT NULL DEFAULT 'system';
ALTER TABLE scenarios ADD COLUMN created_at TEXT;
ALTER TABLE application_settings ADD COLUMN created_by_user_id TEXT NOT NULL DEFAULT 'system';
ALTER TABLE application_settings ADD COLUMN created_at TEXT;
ALTER TABLE imports ADD COLUMN created_by_user_id TEXT NOT NULL DEFAULT 'system';
ALTER TABLE imports ADD COLUMN created_at_metadata TEXT;
ALTER TABLE import_rows ADD COLUMN created_by_user_id TEXT NOT NULL DEFAULT 'system';
ALTER TABLE import_rows ADD COLUMN created_at TEXT;
ALTER TABLE audit_events ADD COLUMN created_by_user_id TEXT NOT NULL DEFAULT 'system';
ALTER TABLE idempotency_keys ADD COLUMN created_by_user_id TEXT NOT NULL DEFAULT 'system';
ALTER TABLE idempotency_keys ADD COLUMN created_at TEXT;
UPDATE categories SET created_at = coalesce(json_extract(payload, '$.createdAt'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now'));
UPDATE transactions SET created_at = coalesce(json_extract(payload, '$.createdAt'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now'));
UPDATE budgets SET created_at = coalesce(json_extract(payload, '$.createdAt'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now'));
UPDATE recurring_commitments SET created_at = coalesce(json_extract(payload, '$.createdAt'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now'));
UPDATE categorization_rules SET created_at = coalesce(json_extract(payload, '$.createdAt'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now'));
UPDATE legacy_exchange_rates SET created_at = coalesce(json_extract(payload, '$.createdAt'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now'));
UPDATE scenarios SET created_at = coalesce(json_extract(payload, '$.createdAt'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now'));
UPDATE application_settings SET created_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now');
UPDATE imports SET created_at_metadata = created_at;
UPDATE import_rows SET created_at = (SELECT created_at FROM imports WHERE imports.id = import_rows.import_id);
UPDATE idempotency_keys SET created_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now');
CREATE INDEX transactions_creator ON transactions(created_by_user_id);
CREATE INDEX imports_creator ON imports(created_by_user_id);
